config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'statics#index'

  get 'products/itemsnew'
  resources :statics
  resources :products
  resources :productattributes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :product_attributes , dependent: :destroy, :foreign_key => :value, :primary_key => :value
end

app/models/product_attribute.rb
class ProductAttribute < ApplicationRecord
	belongs_to :product, :foreign_key => :value, :primary_key => :value
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


	def index
		@products = ProductAttribute.all
	end

	def itemsnew
		@product = ProductAttribute.new
	end

	def new
		@product = ProductAttribute.new
	end

	def edit
		@product = ProductAttribute.find(params[:id])
	end

	def show
		@product = ProductAttribute.find(params[:id])
	end

	def update
		@product = ProductAttribute.find(params[:id])
		if @product.update(product_params)
			if params[:val] == "true"
				redirect_to product_path
			else
				redirect_to products_url
			end
		else
			render 'edit'
		end
	end

	def create
		@product = ProductAttribute.new(product_params)
		if @product.save
			if params[:val] == "true"
				prod_id = Product.find_by(value: @product.value) 
				redirect_to static_path(prod_id.id)
			else
				redirect_to products_url
			end
		else
			redirect_to new_product_url
		end
	end

	def destroy
		@product = ProductAttribute.find(params[:id])
		@product.destroy
		if params[:val] == "true"
			prod_id = Product.find_by(value: @product.value) 
			redirect_to static_path(prod_id.id)
		else
			redirect_to products_url
		end
	end

	private

	def product_params
		params.require(:product_attribute).permit(:name,:value,:size,:description,:image)
	end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def show
		@product = Product.find(params[:id])
		@attributes = ProductAttribute.where(value: @product.value)
	end
	
	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to root_url
		else
			render 'edit'
		end
	end

	def destroy
		Product.find(params[:id]).destroy
		redirect_to root_url
	end

	private

		def product_params
			params.require(:product).permit(:name,:value)
		end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			<li><%= link_to "About", '#' %></li>
			<li><%= link_to "Contact", '#' %></li>
		</ul>
	</nav>
	&copy: copyright BuildMyPC 2017
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "BuildMyPc", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_defaults.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
   	<script scr="//cdnjs.cloudfare.com/ajax/libs/html5shiv/r29/html5.min.js">
   	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testing</title>
    <%= render 'layouts/rails_defaults'%>
    <%= render 'layouts/shim' %>
  </head>

  <body>
	<%= render 'layouts/header' %>
	    <div class="container">
	      <%= yield %>
	    </div>
	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product Items </h1>

<%= form_for(@product, url: product_path(@product,val: params[:val]), method: :patch, html: { multipart: true }) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name , class: 'form-control' %>

	<%= f.label :value %>
	<%= f.number_field :value , class: 'form-control' %>

	<%= f.label :size %>
	<%= f.text_field :size, class: 'form-control' %>

	<%= f.label :description %>
	<%= f.text_field :description, class: 'form-control' %>

	<%= f.hidden_field(:image_cache) %>
	<%= f.file_field(:image) %>

	<%= f.submit "Update", class: 'btn btn-primary' %>
<% end %>

app/views/products/index.html.erb
<h1>Listing all the Product Items</h1>

<% @products.each do |product| %>
	<l1> <%= product.name %> </l1>
	<li> <%= image_tag(product.image.url(:thumbnail)) %> </li>
	<l1> <%= link_to "Edit", edit_product_path(product) %></l1>
	<li> <%= link_to "Delete", product_path(product) , method: :delete, data: {confirm: "are u sure?"} %> </l1>
<% end %>

<h3><%= link_to "Create Product Items", products_itemsnew_path %></h3>

app/views/products/itemsnew.html.erb
<h1>Add the New Product Attribute</h1>

<%= form_for(@product, url: products_path) do |f|%>
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :value %>
	<%= f.number_field :value, class: 'form-control' %>

	<%= f.label :size %>
	<%= f.text_field :size, class: 'form-control' %>

	<%= f.label :description %>
	<%= f.text_field :description, class: 'form-control' %>

	<%= f.hidden_field(:image_cache) %>
	<%= f.file_field(:image)%>

	<%= f.submit "Create", class: 'btn btn-primary' %>
<% end %>

app/views/products/new.html.erb
<h1>Add the New Product Attribute</h1>

<%= form_for(@product, url: products_path(@product, val: "true"), html: { multipart: true }) do |f|%>
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.hidden_field :value, :value => params[:value] %>

	<%= f.label :size %>
	<%= f.text_field :size, class: 'form-control' %>

	<%= f.label :description %>
	<%= f.text_field :description, class: 'form-control' %>

	<%= f.hidden_field(:image_cache) %>
	<%= f.file_field(:image) %>

	<%= f.submit "Create", class: 'btn btn-primary' %>
<% end %>

app/views/products/show.html.erb
<%= image_tag(@product.image_url(:thumbnail), :width => 50, :height => 50) %>
<h1><%= @product.name %></h1>
<h3><%= @product.description %></h3>

app/views/statics/edit.html.erb
<h1> Edit Product </h1>

<%= form_for(@product, url: static_path, method: :patch) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :value %>
	<%= f.text_field :value, class: 'form-control' %>

	<%= f.submit "Update", class: "btn btn-primary" %>
<% end %>

app/views/statics/index.html.erb
<h1>Listing the products in home page</h1>

<% @products.each do |product| %>
	<li><%=link_to product.name, static_path(product)%>    <%= link_to "Edit", edit_static_path(product) %>    <%= link_to "Delete", static_path(product) , method: :delete, data: {confirm: "are u sure?"} %> </l1>
<% end %>

<h3><%= link_to "New Product", new_static_path %></h3>
	<h3><%= link_to   "Product Attributes List", products_path %></h3>

app/views/statics/new.html.erb
<h1> New Product Creation </h1>

<%= form_for(@product, url: statics_create_path) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :value %>
	<%= f.text_field :value, class: 'form-control' %>

	<%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/statics/show.html.erb
<h1>Product listing now(only field)</h1>

<% @attributes.each do |attribute| %>
	<li><%= link_to attribute.name, product_path(attribute)%><%= image_tag(attribute.image_url(:thumbnail)) %>  <%= link_to 'Edit', edit_product_path(attribute, val: "true")%>  <%= link_to 'Delete', product_path(attribute, val: "true"), method: :delete, data: {confirm: "are u sure?"}%></li>
<% end %>

<h4><%= link_to "Create New Product Attributes", new_product_path(value: @product.value) %></h4>